
# minikube service app-js-cluster-ip --url
apiVersion: v1
kind: Service
metadata:
  name: app-js-cluster-ip
spec:
  selector:
    app: app-js-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30007
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-js-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-js-deployment
  template:
    metadata:
      labels:
        app: app-js-deployment
    spec:
      containers:
        - name: app-js
          image: mmat30/app-js:latest 
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "2"
              memory: "2Gi"
            requests:
              cpu: "0.5"
              memory: "1Gi"
          ports:
            - containerPort: 8080
      restartPolicy: Always